#include <stdint.h>
#include <stddef.h>

// -----------------------------
// Memory map
// -----------------------------
#define FLASH_BASE_ADDR      0x08000000u
#define FLASH_END_ADDR       0x08010000u
#define APP_BASE_ADDR        0x08002000u
#define APP_MAX_BYTES        (FLASH_END_ADDR - APP_BASE_ADDR)
#define FLASH_PAGE_BYTES     1024u

// -----------------------------
// Core/system registers
// -----------------------------
#define RCC_BASE             0x40021000u
#define RCC_AHBENR           (*(volatile uint32_t*)(RCC_BASE + 0x14u))
#define RCC_APB2ENR          (*(volatile uint32_t*)(RCC_BASE + 0x18u))
#define RCC_APB1ENR          (*(volatile uint32_t*)(RCC_BASE + 0x1Cu))

#define RCC_AHBENR_GPIOAEN   (1u << 17)
#define RCC_AHBENR_GPIOBEN   (1u << 18)
#define RCC_APB2ENR_SYSCFGEN (1u << 0)
#define RCC_APB1ENR_TIM14EN  (1u << 8)

#define SYSCFG_BASE          0x40010000u
#define SYSCFG_CFGR1         (*(volatile uint32_t*)(SYSCFG_BASE + 0x00u))
#define SYSCFG_EXTICR3       (*(volatile uint32_t*)(SYSCFG_BASE + 0x10u))

#define EXTI_BASE            0x40010400u
#define EXTI_IMR             (*(volatile uint32_t*)(EXTI_BASE + 0x00u))
#define EXTI_RTSR            (*(volatile uint32_t*)(EXTI_BASE + 0x08u))
#define EXTI_FTSR            (*(volatile uint32_t*)(EXTI_BASE + 0x0Cu))
#define EXTI_PR              (*(volatile uint32_t*)(EXTI_BASE + 0x14u))

#define NVIC_ISER            (*(volatile uint32_t*)0xE000E100u)

#define GPIOA_BASE           0x48000000u
#define GPIOA_MODER          (*(volatile uint32_t*)(GPIOA_BASE + 0x00u))
#define GPIOA_PUPDR          (*(volatile uint32_t*)(GPIOA_BASE + 0x0Cu))
#define GPIOA_IDR            (*(volatile uint32_t*)(GPIOA_BASE + 0x10u))
#define GPIOA_BSRR           (*(volatile uint32_t*)(GPIOA_BASE + 0x18u))

#define GPIOB_BASE           0x48000400u
#define GPIOB_MODER          (*(volatile uint32_t*)(GPIOB_BASE + 0x00u))
#define GPIOB_BSRR           (*(volatile uint32_t*)(GPIOB_BASE + 0x18u))

#define TIM14_BASE           0x40002000u
#define TIM14_CR1            (*(volatile uint32_t*)(TIM14_BASE + 0x00u))
#define TIM14_CNT            (*(volatile uint32_t*)(TIM14_BASE + 0x24u))
#define TIM14_PSC            (*(volatile uint32_t*)(TIM14_BASE + 0x28u))
#define TIM14_ARR            (*(volatile uint32_t*)(TIM14_BASE + 0x2Cu))

#define FLASH_IF_BASE        0x40022000u
#define FLASH_KEYR           (*(volatile uint32_t*)(FLASH_IF_BASE + 0x04u))
#define FLASH_SR             (*(volatile uint32_t*)(FLASH_IF_BASE + 0x0Cu))
#define FLASH_CR             (*(volatile uint32_t*)(FLASH_IF_BASE + 0x10u))
#define FLASH_AR             (*(volatile uint32_t*)(FLASH_IF_BASE + 0x14u))

#define FLASH_KEY1           0x45670123u
#define FLASH_KEY2           0xCDEF89ABu

#define FLASH_SR_BSY         (1u << 0)
#define FLASH_SR_PGERR       (1u << 2)
#define FLASH_SR_WRPRTERR    (1u << 4)
#define FLASH_SR_EOP         (1u << 5)

#define FLASH_CR_PG          (1u << 0)
#define FLASH_CR_PER         (1u << 1)
#define FLASH_CR_STRT        (1u << 6)
#define FLASH_CR_LOCK        (1u << 7)

// -----------------------------
// Pins
// -----------------------------
#define PIN_PA3              3u   // mute button input (active-low)
#define PIN_PA8              8u   // audio/clock input
#define PIN_PA12             12u  // mute LED

static const uint8_t kStepLedPins[8] = { 9u, 10u, 11u, 14u, 13u, 8u, 12u, 15u };

// -----------------------------
// Mutable-style FSK symbols
// -----------------------------
#define SYMBOL_0                0u
#define SYMBOL_1                1u
#define SYMBOL_PAUSE            2u

// Symbol periods generated by WAV tool:
// 0 -> 64 samples (~1333 us), 1 -> 128 samples (~2667 us), pause -> 512 samples (~10667 us)
#define FSK_ZERO_ONE_THRESH_US  2000u
#define FSK_ONE_PAUSE_THRESH_US 6667u
#define FSK_GLITCH_US            300u
#define FSK_TIMEOUT_US         18000u
#define FSK_SWALLOW_SYMBOLS      4u

#define PACKET_SIZE_BYTES        256u
#define PACKET_TOTAL_BYTES       (PACKET_SIZE_BYTES + 4u)
#define PREAMBLE_SYMBOLS         32u
#define MIN_SYNC_PAUSES          2u
#define MAX_SYNC_BLANK_SYMBOLS   500u

#define HEADER_MAGIC             0x31495249u  // "IRI1" little-endian in packet[0..3]

// Boot behavior
#define RX_IDLE_ABORT_MS     3000u
#define UPDATE_DONE_HOLD_MS  1000u
#define BOOT_TEST_ALWAYS     0u

#define SRAM_BASE            0x20000000u
#define SRAM_END             0x20002000u

typedef void (*entry_fn_t)(void);

static inline void set_msp(uint32_t top_of_main_stack) {
    __asm volatile ("msr msp, %0" : : "r" (top_of_main_stack) : );
}

static inline void disable_irq(void) {
    __asm volatile ("cpsid i" ::: "memory");
}

static inline void enable_irq(void) {
    __asm volatile ("cpsie i" ::: "memory");
}

static uint8_t is_valid_app(uint32_t sp, uint32_t reset) {
    if (sp < SRAM_BASE || sp > SRAM_END) return 0u;
    if (reset < APP_BASE_ADDR || reset >= FLASH_END_ADDR) return 0u;
    if (sp == 0xFFFFFFFFu || reset == 0xFFFFFFFFu) return 0u;
    return 1u;
}

static void remap_vector_table_to_sram(const uint32_t* app_vectors) {
    volatile uint32_t* sram_vectors = (uint32_t*)SRAM_BASE;
    for (uint32_t i = 0u; i < 48u; ++i) {
        sram_vectors[i] = app_vectors[i];
    }

    RCC_APB2ENR |= RCC_APB2ENR_SYSCFGEN;
    SYSCFG_CFGR1 = (SYSCFG_CFGR1 & ~0x3u) | 0x3u; // MEM_MODE = SRAM @ 0x00000000
}

static void jump_to_app(void) {
    uint32_t* app = (uint32_t*)APP_BASE_ADDR;
    const uint32_t app_sp = app[0];
    const uint32_t app_reset = app[1];

    if (!is_valid_app(app_sp, app_reset)) {
        return;
    }

    disable_irq();
    remap_vector_table_to_sram(app);
    set_msp(app_sp);
    ((entry_fn_t)app_reset)();
}

// -----------------------------
// Minimal hardware init
// -----------------------------
static void hw_init(void) {
    RCC_AHBENR |= RCC_AHBENR_GPIOAEN | RCC_AHBENR_GPIOBEN;
    RCC_APB1ENR |= RCC_APB1ENR_TIM14EN;
    RCC_APB2ENR |= RCC_APB2ENR_SYSCFGEN;

    // PA8 input with pull-up.
    GPIOA_MODER &= ~(0x3u << (PIN_PA8 * 2u));
    GPIOA_PUPDR &= ~(0x3u << (PIN_PA8 * 2u));
    GPIOA_PUPDR |=  (0x1u << (PIN_PA8 * 2u));

    // PA3 input with pull-up.
    GPIOA_MODER &= ~(0x3u << (PIN_PA3 * 2u));
    GPIOA_PUPDR &= ~(0x3u << (PIN_PA3 * 2u));
    GPIOA_PUPDR |=  (0x1u << (PIN_PA3 * 2u));

    // PA12 output push-pull.
    GPIOA_MODER &= ~(0x3u << (PIN_PA12 * 2u));
    GPIOA_MODER |=  (0x1u << (PIN_PA12 * 2u));
    GPIOA_BSRR = (1u << (PIN_PA12 + 16u));

    // PB step LEDs (logical 1..8) outputs.
    for (uint8_t i = 0u; i < 8u; ++i) {
        const uint8_t pin = kStepLedPins[i];
        GPIOB_MODER &= ~(0x3u << (pin * 2u));
        GPIOB_MODER |=  (0x1u << (pin * 2u));
        GPIOB_BSRR = (1u << (pin + 16u));
    }

    // TIM14 free-running at 1 MHz (HSI 8 MHz / (PSC+1=8)).
    TIM14_PSC = 7u;
    TIM14_ARR = 0xFFFFu;
    TIM14_CNT = 0u;
    TIM14_CR1 = 1u;

    // EXTI line8 from PA8, both edges.
    SYSCFG_EXTICR3 &= ~(0xFu << 0u); // EXTI8 -> PA8
    EXTI_IMR  |= (1u << PIN_PA8);
    EXTI_RTSR |= (1u << PIN_PA8);
    EXTI_FTSR |= (1u << PIN_PA8);
    EXTI_PR = (1u << PIN_PA8);

    // EXTI4_15 IRQ enable (IRQn=7).
    NVIC_ISER = (1u << 7);
}

static inline uint8_t read_pa8(void) {
    return (uint8_t)((GPIOA_IDR >> PIN_PA8) & 0x1u);
}

static inline uint8_t read_pa3_pressed(void) {
    return (uint8_t)(((GPIOA_IDR >> PIN_PA3) & 0x1u) == 0u);
}

static inline void status_led_set(uint8_t on) {
    if (on) {
        GPIOA_BSRR = (1u << PIN_PA12);
    } else {
        GPIOA_BSRR = (1u << (PIN_PA12 + 16u));
    }
}

static inline void step_led_set(uint8_t index, uint8_t on) {
    if (index >= 8u) return;
    const uint8_t pin = kStepLedPins[index];
    if (on) {
        GPIOB_BSRR = (1u << pin);
    } else {
        GPIOB_BSRR = (1u << (pin + 16u));
    }
}

static void step_leds_all(uint8_t on) {
    for (uint8_t i = 0u; i < 8u; ++i) {
        step_led_set(i, on);
    }
}

static void step_leds_progress(uint32_t done, uint32_t total) {
    uint8_t lit = 0u;
    if (total != 0u) {
        lit = (uint8_t)((done * 8u) / total);
        if (done >= total) {
            lit = 8u;
        }
    }
    for (uint8_t i = 0u; i < 8u; ++i) {
        step_led_set(i, (uint8_t)(i < lit));
    }
}

// -----------------------------
// Timebase from TIM14
// -----------------------------
static uint16_t g_last_tim14 = 0u;
static uint32_t g_time_us = 0u;

static void time_init(void) {
    g_last_tim14 = (uint16_t)TIM14_CNT;
    g_time_us = 0u;
}

static void time_update(void) {
    const uint16_t now = (uint16_t)TIM14_CNT;
    const uint16_t delta = (uint16_t)(now - g_last_tim14);
    g_last_tim14 = now;
    g_time_us += (uint32_t)delta;
}

static uint32_t now_ms(void) {
    time_update();
    return g_time_us / 1000u;
}

static uint8_t sample_force_boot_latched(void) {
    uint32_t pressed_samples = 0u;
    uint32_t total_samples = 0u;
    const uint32_t start_ms = now_ms();
    while ((now_ms() - start_ms) < 40u) {
        if (read_pa3_pressed()) {
            pressed_samples++;
        }
        total_samples++;
    }
    if (total_samples == 0u) {
        return 0u;
    }
    return (pressed_samples * 4u >= total_samples * 3u) ? 1u : 0u;
}

// -----------------------------
// CRC helpers
// -----------------------------
static uint32_t crc32_flash(uint32_t addr, uint32_t size) {
    uint32_t crc = 0xFFFFFFFFu;
    for (uint32_t i = 0u; i < size; ++i) {
        const uint8_t b = *(volatile const uint8_t*)(addr + i);
        crc ^= (uint32_t)b;
        for (uint8_t j = 0u; j < 8u; ++j) {
            if (crc & 1u) {
                crc = (crc >> 1) ^ 0xEDB88320u;
            } else {
                crc >>= 1;
            }
        }
    }
    return crc ^ 0xFFFFFFFFu;
}

static uint32_t crc32_buf(const uint8_t* data, uint32_t size) {
    uint32_t crc = 0xFFFFFFFFu;
    for (uint32_t i = 0u; i < size; ++i) {
        crc ^= (uint32_t)data[i];
        for (uint8_t j = 0u; j < 8u; ++j) {
            if (crc & 1u) {
                crc = (crc >> 1) ^ 0xEDB88320u;
            } else {
                crc >>= 1;
            }
        }
    }
    return crc ^ 0xFFFFFFFFu;
}

// -----------------------------
// Flash programming helpers
// -----------------------------
static void flash_wait_ready(void) {
    while (FLASH_SR & FLASH_SR_BSY) {
        // wait
    }
}

static uint8_t flash_unlock(void) {
    if (FLASH_CR & FLASH_CR_LOCK) {
        FLASH_KEYR = FLASH_KEY1;
        FLASH_KEYR = FLASH_KEY2;
    }
    return (uint8_t)((FLASH_CR & FLASH_CR_LOCK) == 0u);
}

static void flash_lock(void) {
    FLASH_CR |= FLASH_CR_LOCK;
}

static void flash_clear_status(void) {
    FLASH_SR = FLASH_SR_EOP | FLASH_SR_PGERR | FLASH_SR_WRPRTERR;
}

static uint8_t flash_erase_page(uint32_t addr) {
    flash_wait_ready();
    flash_clear_status();

    FLASH_CR |= FLASH_CR_PER;
    FLASH_AR = addr;
    FLASH_CR |= FLASH_CR_STRT;

    flash_wait_ready();
    FLASH_CR &= ~FLASH_CR_PER;

    if (FLASH_SR & (FLASH_SR_PGERR | FLASH_SR_WRPRTERR)) {
        return 0u;
    }
    flash_clear_status();
    return 1u;
}

static uint8_t flash_program_halfword(uint32_t addr, uint16_t data) {
    flash_wait_ready();
    flash_clear_status();

    FLASH_CR |= FLASH_CR_PG;
    *(volatile uint16_t*)addr = data;
    flash_wait_ready();
    FLASH_CR &= ~FLASH_CR_PG;

    if (FLASH_SR & (FLASH_SR_PGERR | FLASH_SR_WRPRTERR)) {
        return 0u;
    }
    if (*(volatile uint16_t*)addr != data) {
        return 0u;
    }
    flash_clear_status();
    return 1u;
}

// -----------------------------
// Boot diagnostics
// -----------------------------
typedef struct {
    volatile uint32_t magic;
    volatile uint32_t edges;
    volatile uint32_t symbols;
    volatile uint32_t sync_hits;
    volatile uint32_t frames_ok;
    volatile uint32_t crc_fail;
    volatile uint32_t start_fail;
    volatile uint32_t data_fail;
    volatile uint32_t end_fail;
    volatile uint32_t timing_reset;
    volatile uint32_t idle_abort;
    volatile uint32_t bytes_written;
    volatile uint32_t image_size;
    volatile uint32_t image_crc32;
    volatile uint32_t last_error_code;
    volatile uint32_t aux;
} BootDiag;

#define BOOT_DIAG_ADDR       0x20001800u
#define BOOT_DIAG            (*(volatile BootDiag*)BOOT_DIAG_ADDR)

typedef struct {
    volatile uint32_t magic;
    volatile uint32_t rising_edges;
    volatile uint32_t falling_edges;
    volatile uint32_t dt_lt100;
    volatile uint32_t dt_100_250;
    volatile uint32_t dt_250_400;
    volatile uint32_t dt_400_650;
    volatile uint32_t dt_650_900;
    volatile uint32_t dt_900_1300;
    volatile uint32_t dt_1300_2200;
    volatile uint32_t dt_ge2200;
    volatile uint32_t dt_min;
    volatile uint32_t dt_max;
    volatile uint32_t dt_last;
    volatile uint32_t stream_select;
    volatile uint32_t rise_score;
    volatile uint32_t fall_score;
} BootEdgeDiag;

#define BOOT_EDGE_DIAG_ADDR  0x20001880u
#define BOOT_EDGE_DIAG       (*(volatile BootEdgeDiag*)BOOT_EDGE_DIAG_ADDR)

// -----------------------------
// Symbol queue
// -----------------------------
#define SYMBOL_QUEUE_SIZE    1024u
static volatile uint8_t g_symbol_queue[SYMBOL_QUEUE_SIZE];
static volatile uint16_t g_symbol_head = 0u;
static volatile uint16_t g_symbol_tail = 0u;
static volatile uint8_t g_symbol_overflow = 0u;

static inline void symbol_queue_reset(void) {
    g_symbol_head = 0u;
    g_symbol_tail = 0u;
    g_symbol_overflow = 0u;
}

static inline void symbol_queue_push_isr(uint8_t sym) {
    const uint16_t next = (uint16_t)((g_symbol_head + 1u) & (SYMBOL_QUEUE_SIZE - 1u));
    if (next == g_symbol_tail) {
        g_symbol_overflow = 1u;
        return;
    }
    g_symbol_queue[g_symbol_head] = sym;
    g_symbol_head = next;
}

static uint8_t symbol_queue_pop(uint8_t* sym) {
    if (g_symbol_tail == g_symbol_head) {
        return 0u;
    }
    *sym = g_symbol_queue[g_symbol_tail];
    g_symbol_tail = (uint16_t)((g_symbol_tail + 1u) & (SYMBOL_QUEUE_SIZE - 1u));
    return 1u;
}

// -----------------------------
// Mutable-style packet decoder
// -----------------------------
enum PacketDecoderState {
    PACKET_DECODER_STATE_SYNCING = 0,
    PACKET_DECODER_STATE_DECODING_PACKET,
    PACKET_DECODER_STATE_OK,
    PACKET_DECODER_STATE_ERROR_SYNC,
    PACKET_DECODER_STATE_ERROR_CRC,
    PACKET_DECODER_STATE_END_OF_TRANSMISSION
};

static volatile enum PacketDecoderState g_pkt_state = PACKET_DECODER_STATE_SYNCING;
static uint8_t g_expected_symbols = 0xFFu;
static uint8_t g_preamble_remaining = PREAMBLE_SYMBOLS;
static uint16_t g_sync_blank_size = 0u;
static uint8_t g_sync_armed = 0u;
static uint8_t g_symbol_count = 0u;
static uint16_t g_packet_size = 0u;
static uint16_t g_packet_count = 0u;
static uint8_t g_packet[PACKET_TOTAL_BYTES];

static void packet_decoder_init(void) {
    g_pkt_state = PACKET_DECODER_STATE_SYNCING;
    g_expected_symbols = 0xFFu;
    g_preamble_remaining = PREAMBLE_SYMBOLS;
    g_sync_blank_size = 0u;
    g_sync_armed = 0u;
    g_symbol_count = 0u;
    g_packet_size = 0u;
    g_packet_count = 0u;
}

static void packet_decoder_reset_to_sync(void) {
    g_pkt_state = PACKET_DECODER_STATE_SYNCING;
    g_expected_symbols = 0xFFu;
    g_preamble_remaining = PREAMBLE_SYMBOLS;
    g_sync_blank_size = 0u;
    g_sync_armed = 0u;
    g_symbol_count = 0u;
    g_packet_size = 0u;
}

static void packet_decoder_parse_sync(uint8_t symbol) {
    switch (symbol) {
    case SYMBOL_PAUSE:
        g_sync_blank_size++;
        if (g_sync_blank_size >= MAX_SYNC_BLANK_SYMBOLS && g_packet_count != 0u) {
            g_pkt_state = PACKET_DECODER_STATE_END_OF_TRANSMISSION;
            return;
        }
        if (g_sync_blank_size >= MIN_SYNC_PAUSES) {
            g_sync_armed = 1u;
            g_expected_symbols = (uint8_t)((1u << SYMBOL_0) | (1u << SYMBOL_1));
            g_preamble_remaining = PREAMBLE_SYMBOLS;
        }
        break;

    case SYMBOL_1:
    case SYMBOL_0:
    default:
        if (!g_sync_armed) {
            g_sync_blank_size = 0u;
            break;
        }
        if (((uint8_t)(1u << symbol) & g_expected_symbols) == 0u) {
            // Bad preamble symbol: disarm and wait for next blank run.
            g_sync_armed = 0u;
            g_sync_blank_size = 0u;
            g_expected_symbols = 0xFFu;
            g_preamble_remaining = PREAMBLE_SYMBOLS;
            break;
        }

        g_sync_blank_size = 0u;
        if (symbol == SYMBOL_1) {
            g_expected_symbols = (uint8_t)(1u << SYMBOL_0);
        } else {
            g_expected_symbols = (uint8_t)(1u << SYMBOL_1);
        }

        if (g_preamble_remaining != 0u) {
            g_preamble_remaining--;
        }
        break;
    }

    if (g_preamble_remaining == 0u) {
        g_pkt_state = PACKET_DECODER_STATE_DECODING_PACKET;
        g_packet_size = 0u;
        g_packet[g_packet_size] = 0u;
        g_symbol_count = 0u;
        BOOT_DIAG.sync_hits++;
    }
}

static enum PacketDecoderState packet_decoder_process_symbol(uint8_t symbol) {
    switch (g_pkt_state) {
    case PACKET_DECODER_STATE_SYNCING:
        packet_decoder_parse_sync(symbol);
        break;

    case PACKET_DECODER_STATE_DECODING_PACKET:
        if (symbol == SYMBOL_PAUSE) {
            g_pkt_state = PACKET_DECODER_STATE_ERROR_SYNC;
            break;
        }

        g_packet[g_packet_size] = (uint8_t)((g_packet[g_packet_size] << 1) | (symbol & 1u));
        g_symbol_count++;

        if (g_symbol_count == 8u) {
            g_symbol_count = 0u;
            g_packet_size++;

            if (g_packet_size == PACKET_TOTAL_BYTES) {
                const uint32_t crc = crc32_buf(g_packet, PACKET_SIZE_BYTES);
                const uint32_t expected_crc =
                    ((uint32_t)g_packet[PACKET_SIZE_BYTES + 0u] << 24) |
                    ((uint32_t)g_packet[PACKET_SIZE_BYTES + 1u] << 16) |
                    ((uint32_t)g_packet[PACKET_SIZE_BYTES + 2u] << 8)  |
                    ((uint32_t)g_packet[PACKET_SIZE_BYTES + 3u] << 0);

                if (crc == expected_crc) {
                    g_pkt_state = PACKET_DECODER_STATE_OK;
                    BOOT_DIAG.aux = 0u;
                } else {
                    g_pkt_state = PACKET_DECODER_STATE_ERROR_CRC;
                }
                g_packet_count++;
            } else {
                g_packet[g_packet_size] = 0u;
            }
        }
        break;

    case PACKET_DECODER_STATE_OK:
    case PACKET_DECODER_STATE_ERROR_SYNC:
    case PACKET_DECODER_STATE_ERROR_CRC:
    case PACKET_DECODER_STATE_END_OF_TRANSMISSION:
    default:
        break;
    }

    return g_pkt_state;
}

// -----------------------------
// Demod state (edge-timed)
// -----------------------------
static volatile uint8_t g_have_edge = 0u;
static volatile uint16_t g_last_edge_tick = 0u;
static volatile uint8_t g_swallow = FSK_SWALLOW_SYMBOLS;
static volatile uint8_t g_pa8_seen = 0u;

static inline uint8_t classify_symbol(uint16_t dt) {
    if (dt >= FSK_ONE_PAUSE_THRESH_US) {
        return SYMBOL_PAUSE;
    }
    if (dt >= FSK_ZERO_ONE_THRESH_US) {
        return SYMBOL_1;
    }
    return SYMBOL_0;
}

static inline void duration_hist_update(uint16_t dt) {
    BOOT_EDGE_DIAG.dt_last = dt;
    if (dt < BOOT_EDGE_DIAG.dt_min) {
        BOOT_EDGE_DIAG.dt_min = dt;
    }
    if (dt > BOOT_EDGE_DIAG.dt_max) {
        BOOT_EDGE_DIAG.dt_max = dt;
    }

    if (dt < 100u) {
        BOOT_EDGE_DIAG.dt_lt100++;
    } else if (dt < 250u) {
        BOOT_EDGE_DIAG.dt_100_250++;
    } else if (dt < 400u) {
        BOOT_EDGE_DIAG.dt_250_400++;
    } else if (dt < 650u) {
        BOOT_EDGE_DIAG.dt_400_650++;
    } else if (dt < 900u) {
        BOOT_EDGE_DIAG.dt_650_900++;
    } else if (dt < 1300u) {
        BOOT_EDGE_DIAG.dt_900_1300++;
    } else if (dt < 2200u) {
        BOOT_EDGE_DIAG.dt_1300_2200++;
    } else {
        BOOT_EDGE_DIAG.dt_ge2200++;
    }
}

void EXTI4_15_IRQHandler(void) {
    const uint32_t bit = (1u << PIN_PA8);
    if ((EXTI_PR & bit) == 0u) {
        return;
    }
    EXTI_PR = bit;

    const uint8_t level = read_pa8();
    g_pa8_seen = 1u;
    BOOT_DIAG.edges++;
    if (level) {
        BOOT_EDGE_DIAG.rising_edges++;
    } else {
        BOOT_EDGE_DIAG.falling_edges++;
    }

    const uint16_t now = (uint16_t)TIM14_CNT;
    if (!g_have_edge) {
        g_have_edge = 1u;
        g_last_edge_tick = now;
        return;
    }

    const uint16_t dt = (uint16_t)(now - g_last_edge_tick);
    g_last_edge_tick = now;

    if (dt < FSK_GLITCH_US) {
        return;
    }

    duration_hist_update(dt);

    uint8_t symbol;
    if (dt >= FSK_TIMEOUT_US) {
        symbol = SYMBOL_PAUSE;
        g_swallow = FSK_SWALLOW_SYMBOLS;
        BOOT_DIAG.timing_reset++;
    } else {
        symbol = classify_symbol(dt);
    }

    if (g_swallow != 0u) {
        symbol = SYMBOL_PAUSE;
        g_swallow--;
    }

    symbol_queue_push_isr(symbol);
    BOOT_DIAG.symbols++;
    BOOT_DIAG.aux = symbol;
}

// -----------------------------
// Update session state
// -----------------------------
static uint8_t g_update_started = 0u;
static uint8_t g_update_done = 0u;
static uint8_t g_update_error = 0u;
static uint32_t g_update_done_ms = 0u;

static uint32_t g_image_size = 0u;
static uint32_t g_image_crc32 = 0u;
static uint32_t g_bytes_written = 0u;
static uint32_t g_write_addr = APP_BASE_ADDR;
static uint8_t g_pending_valid = 0u;
static uint8_t g_pending_byte = 0u;

static uint32_t g_last_activity_ms = 0u;

static uint32_t load_le32(const uint8_t* p) {
    return ((uint32_t)p[0]) |
           ((uint32_t)p[1] << 8) |
           ((uint32_t)p[2] << 16) |
           ((uint32_t)p[3] << 24);
}

static void abort_update(uint32_t error_code) {
    flash_lock();
    g_update_started = 0u;
    g_update_error = 1u;
    BOOT_DIAG.last_error_code = error_code;
}

static uint8_t begin_update_from_header(const uint8_t* pkt) {
    const uint32_t magic = load_le32(&pkt[0]);
    const uint32_t size = load_le32(&pkt[4]);
    const uint32_t crc = load_le32(&pkt[8]);

    if (magic != HEADER_MAGIC || size == 0u || size > APP_MAX_BYTES) {
        return 0u;
    }

    if (!flash_unlock()) {
        return 0u;
    }

    const uint32_t erase_bytes = (size + FLASH_PAGE_BYTES - 1u) & ~(FLASH_PAGE_BYTES - 1u);
    const uint32_t erase_end = APP_BASE_ADDR + erase_bytes;
    for (uint32_t addr = APP_BASE_ADDR; addr < erase_end; addr += FLASH_PAGE_BYTES) {
        if (!flash_erase_page(addr)) {
            flash_lock();
            return 0u;
        }
    }

    g_image_size = size;
    g_image_crc32 = crc;
    g_bytes_written = 0u;
    g_write_addr = APP_BASE_ADDR;
    g_pending_valid = 0u;
    g_pending_byte = 0u;

    g_update_started = 1u;
    g_update_done = 0u;
    g_update_error = 0u;
    g_update_done_ms = 0u;

    BOOT_DIAG.image_size = size;
    BOOT_DIAG.image_crc32 = crc;
    BOOT_DIAG.bytes_written = 0u;
    BOOT_DIAG.last_error_code = 0u;

    return 1u;
}

static uint8_t flush_pending_halfword(void) {
    if (!g_pending_valid) {
        return 1u;
    }

    const uint16_t hw = (uint16_t)g_pending_byte | 0xFF00u;
    if (!flash_program_halfword(g_write_addr, hw)) {
        return 0u;
    }

    g_write_addr += 2u;
    g_pending_valid = 0u;
    return 1u;
}

static uint8_t write_stream_bytes(const uint8_t* data, uint16_t len) {
    for (uint16_t i = 0u; i < len; ++i) {
        if (g_bytes_written >= g_image_size) {
            break;
        }

        const uint8_t b = data[i];
        if (!g_pending_valid) {
            g_pending_byte = b;
            g_pending_valid = 1u;
        } else {
            const uint16_t hw = (uint16_t)g_pending_byte | ((uint16_t)b << 8);
            if (!flash_program_halfword(g_write_addr, hw)) {
                return 0u;
            }
            g_write_addr += 2u;
            g_pending_valid = 0u;
        }

        g_bytes_written++;
    }

    BOOT_DIAG.bytes_written = g_bytes_written;
    return 1u;
}

static uint8_t finalize_update_if_complete(void) {
    if (!g_update_started || g_bytes_written < g_image_size) {
        return 1u;
    }

    if (!flush_pending_halfword()) {
        return 0u;
    }

    flash_lock();

    const uint32_t crc = crc32_flash(APP_BASE_ADDR, g_image_size);
    if (crc != g_image_crc32) {
        return 0u;
    }

    uint32_t* app = (uint32_t*)APP_BASE_ADDR;
    if (!is_valid_app(app[0], app[1])) {
        return 0u;
    }

    g_update_done = 1u;
    g_update_done_ms = now_ms();
    g_update_started = 0u;
    return 1u;
}

static uint8_t process_data_packet(const uint8_t* pkt) {
    if (!g_update_started) {
        return 0u;
    }

    if (!write_stream_bytes(pkt, PACKET_SIZE_BYTES)) {
        return 0u;
    }

    if (!finalize_update_if_complete()) {
        return 0u;
    }

    return 1u;
}

static uint8_t handle_packet(const uint8_t* pkt) {
    if (load_le32(&pkt[0]) == HEADER_MAGIC) {
        if (!begin_update_from_header(pkt)) {
            BOOT_DIAG.start_fail++;
            BOOT_DIAG.last_error_code = 2u;
            return 0u;
        }
        return 1u;
    }

    if (!g_update_started) {
        return 1u;
    }

    if (!process_data_packet(pkt)) {
        BOOT_DIAG.data_fail++;
        BOOT_DIAG.last_error_code = 3u;
        return 0u;
    }

    return 1u;
}

int main(void) {
    hw_init();
    time_init();
    symbol_queue_reset();
    packet_decoder_init();

    BOOT_DIAG.magic = 0x49314244u; // "I1BD"
    BOOT_DIAG.edges = 0u;
    BOOT_DIAG.symbols = 0u;
    BOOT_DIAG.sync_hits = 0u;
    BOOT_DIAG.frames_ok = 0u;
    BOOT_DIAG.crc_fail = 0u;
    BOOT_DIAG.start_fail = 0u;
    BOOT_DIAG.data_fail = 0u;
    BOOT_DIAG.end_fail = 0u;
    BOOT_DIAG.timing_reset = 0u;
    BOOT_DIAG.idle_abort = 0u;
    BOOT_DIAG.bytes_written = 0u;
    BOOT_DIAG.image_size = 0u;
    BOOT_DIAG.image_crc32 = 0u;
    BOOT_DIAG.last_error_code = 0u;
    BOOT_DIAG.aux = 0u;

    BOOT_EDGE_DIAG.magic = 0x45314447u; // "E1DG"
    BOOT_EDGE_DIAG.rising_edges = 0u;
    BOOT_EDGE_DIAG.falling_edges = 0u;
    BOOT_EDGE_DIAG.dt_lt100 = 0u;
    BOOT_EDGE_DIAG.dt_100_250 = 0u;
    BOOT_EDGE_DIAG.dt_250_400 = 0u;
    BOOT_EDGE_DIAG.dt_400_650 = 0u;
    BOOT_EDGE_DIAG.dt_650_900 = 0u;
    BOOT_EDGE_DIAG.dt_900_1300 = 0u;
    BOOT_EDGE_DIAG.dt_1300_2200 = 0u;
    BOOT_EDGE_DIAG.dt_ge2200 = 0u;
    BOOT_EDGE_DIAG.dt_min = 0xFFFFFFFFu;
    BOOT_EDGE_DIAG.dt_max = 0u;
    BOOT_EDGE_DIAG.dt_last = 0u;
    BOOT_EDGE_DIAG.stream_select = 0u;
    BOOT_EDGE_DIAG.rise_score = 0u;
    BOOT_EDGE_DIAG.fall_score = 0u;

    g_have_edge = 0u;
    g_last_edge_tick = 0u;
    g_swallow = FSK_SWALLOW_SYMBOLS;
    g_pa8_seen = 0u;

    const uint32_t* app = (const uint32_t*)APP_BASE_ADDR;
    const uint8_t app_valid = is_valid_app(app[0], app[1]);
    const uint8_t force_boot_button = sample_force_boot_latched();
    const uint8_t force_boot = (BOOT_TEST_ALWAYS != 0u) ? 1u : force_boot_button;

    // Production behavior: if button is not held, jump straight to main app.
    // This prevents any bootloader blink pattern from appearing during normal power-up.
    if (app_valid && !force_boot) {
        jump_to_app();
    }

    g_last_activity_ms = now_ms();
    uint32_t last_led_toggle_ms = g_last_activity_ms;
    uint8_t led_state = 0u;

    enable_irq();

    while (1) {
        const uint32_t ms = now_ms();

        uint8_t symbol = 0u;
        while (symbol_queue_pop(&symbol)) {
            g_last_activity_ms = ms;

            const enum PacketDecoderState s = packet_decoder_process_symbol(symbol);
            if (s == PACKET_DECODER_STATE_OK) {
                if (handle_packet(g_packet)) {
                    BOOT_DIAG.frames_ok++;
                    BOOT_DIAG.last_error_code = 0u;
                } else {
                    abort_update(8u);
                }
                packet_decoder_reset_to_sync();
            } else if (s == PACKET_DECODER_STATE_ERROR_CRC) {
                BOOT_DIAG.crc_fail++;
                packet_decoder_reset_to_sync();
                if (g_update_started) {
                    abort_update(4u);
                }
            } else if (s == PACKET_DECODER_STATE_ERROR_SYNC) {
                packet_decoder_reset_to_sync();
                if (g_update_started) {
                    abort_update(5u);
                }
            } else if (s == PACKET_DECODER_STATE_END_OF_TRANSMISSION) {
                packet_decoder_reset_to_sync();
                BOOT_DIAG.end_fail++;
                if (g_update_started) {
                    abort_update(6u);
                }
            }
        }

        if (g_symbol_overflow) {
            g_symbol_overflow = 0u;
            BOOT_DIAG.last_error_code = 9u;
            if (g_update_started) {
                abort_update(9u);
            }
            packet_decoder_reset_to_sync();
            symbol_queue_reset();
        }

        if (g_update_done) {
            status_led_set(1u);
            step_leds_all(1u);
            if ((ms - g_update_done_ms) >= UPDATE_DONE_HOLD_MS) {
                jump_to_app();
                g_update_done = 0u;
            }
            continue;
        }

        if (g_update_started && (ms - g_last_activity_ms) > RX_IDLE_ABORT_MS) {
            BOOT_DIAG.idle_abort++;
            abort_update(7u);
            packet_decoder_reset_to_sync();
            symbol_queue_reset();
        }

        status_led_set(1u);
        if (g_update_started) {
            step_leds_progress(g_bytes_written, g_image_size);
        } else if (g_update_error) {
            if ((ms - last_led_toggle_ms) >= 120u) {
                last_led_toggle_ms = ms;
                led_state ^= 1u;
                step_leds_all(led_state);
            }
        } else {
            // Bootloader idle indicator (only visible when boot mode is forced).
            if ((ms - last_led_toggle_ms) >= 250u) {
                last_led_toggle_ms = ms;
                led_state ^= 1u;
            }
            step_leds_all(0u);
            step_led_set(0u, led_state);
            step_led_set(1u, g_pa8_seen);
        }
    }
}
